---
title: "process control organoids"
output: 
  html_document:
    df_print: paged
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache=TRUE, cache.lazy=FALSE, message=FALSE, warning=FALSE)
library(Seurat)
library(dplyr)
library(stringr)
library(ggplot2)
library(cowplot)
library(igraph)
library(Matrix)
library(tidyr)
library(openxlsx)
library(DESeq2)
library(dendextend)
options(future.globals.maxSize = 10 * 1024 * 1024^2)
```

```{r get_data}
samples <- c(paste(outer(c('AO15','AO16','AO22'),c('HT2','pool'),FUN=paste,sep='_'),'16h_control',sep='_'))

sobjs <- list()
for (sample in samples) {
  dge <- Read10X_h5(file.path('..','data','cellbender',paste0(sample,'_filtered.h5')))
  colnames(dge) <- paste0(gsub('_','-',sample),'_',colnames(dge))
  sobjs[[sample]] <- CreateSeuratObject(dge,project=sample,
                                        assay='RNA',min.cells=1,min.features=500)
}

sobj <- merge(sobjs[[samples[1]]],sobjs[samples[2:length(samples)]])

sobj[['donor']] <-  gsub('(AO[0-9]*)-([poolHT280]*)-([516hd]*)-([controlH3N2]*)','\\1',
                         sobj@meta.data$orig.ident)
sobj[['protocol']] <-  gsub('(AO[0-9]*)-([poolHT280]*)-([516hd]*)-([controlH3N2]*)','\\2',
                         sobj@meta.data$orig.ident)

sobj[['pct.mito']] <- PercentageFeatureSet(sobj, pattern='^MT-')
sobj[['pct.ribo']] <- PercentageFeatureSet(sobj, pattern='^RP[SL][0-9]*$')
```

```{r stats}
sobj@meta.data %>%
  dplyr::group_by(orig.ident) %>%
  dplyr::summarise(ncells=n(),
                   nGene=median(nFeature_RNA),
                   nUMI=median(nCount_RNA),
                   pct.mito=median(pct.mito),
                   pct.ribo=median(pct.ribo))
```

```{r scatter}
ggplot(sobj@meta.data %>% 
         dplyr::select(orig.ident, nCount_RNA, nFeature_RNA, 
                       pct.mito, pct.ribo) %>%
         gather(metric,value,-orig.ident),
       aes(x=orig.ident,y=value,fill=orig.ident)) + 
  geom_boxplot(outlier.size=.5) + 
  theme_classic() +
  facet_wrap(~metric,ncol=2,scales='free_y') + 
  theme(axis.text.x=element_blank())
```

```{r process}
s.genes <- cc.genes$s.genes
g2m.genes <- cc.genes$g2m.genes

sobj <- subset(sobj, (pct.mito < 10) & (nFeature_RNA < 5000) & (nCount_RNA < 25000)) %>%
  NormalizeData(normalization.method='LogNormalize',scale.factor=10000,verbose=FALSE) %>%
  FindVariableFeatures(selection.method='vst',nfeatures=2000,verbose=FALSE) %>%
  ScaleData(vars.to.regress=c('nCount_RNA'),verbose=FALSE) %>%
  CellCycleScoring(s.features = s.genes, g2m.features = g2m.genes) %>%
  ScaleData(vars.to.regress=c('S.Score','G2M.Score'),verbose=FALSE) %>%
  RunPCA(features=VariableFeatures(.),verbose=FALSE) %>%
  FindNeighbors(dims=1:20,verbose=FALSE) %>%
  RunUMAP(dims=1:20,verbose=FALSE)
```

```{r integrate}
sobjs <- SplitObject(sobj, split.by='orig.ident')
anchors <- FindIntegrationAnchors(sobjs, dims=1:20, verbose=FALSE, reduction='rpca')
sobj <- IntegrateData(anchors, dims=1:20, verbose=FALSE)
DefaultAssay(sobj) <- "integrated"
sobj <- ScaleData(sobj,vars.to.regress=c('S.Score','G2M.Score','nCount_RNA','pct.mito'),
                  verbose = FALSE) %>%
  RunPCA(npcs = 20, verbose = FALSE) %>%
  FindNeighbors(dims=1:20, verbose = FALSE) %>%
  RunUMAP(dims = 1:20, verbose = FALSE) %>%
  FindClusters(resolution=1.0, verbose=FALSE)
```

```{r show}
DimPlot(sobj,reduction='umap',group.by='orig.ident')
DimPlot(sobj,reduction='umap',group.by='protocol')
DimPlot(sobj,reduction='umap',group.by='Phase')
DimPlot(sobj,reduction='umap',label=TRUE)
```

```{r markers}
markers <- FindAllMarkers(sobj, only.pos = TRUE, min.pct = 0.25,
                          thresh.use = 0.25,
                          print.bar=FALSE, verbose=FALSE)

write.csv(markers,file.path('..','data','seurat','organoids_control_markers.csv'),row.names=FALSE)

top5 <- markers %>% 
  group_by(cluster) %>% 
  top_n(5, avg_log2FC)

DotPlot(sobj, features = unique(top5$gene)) + 
  theme(axis.text.x=element_text(angle=90,hjust=1,vjust=.5))
```

```{r doublets}
source('my_doubletFinder.R')
DF <- list()
for (sample in unique(sobj$orig.ident)) {
  tmp <- subset(sobj,subset=orig.ident==sample)
  DefaultAssay(tmp) <- 'RNA'
  homotypic.prop <- modelHomotypic(Idents(tmp))
  nExp_poi <- round(0.05*nrow(tmp@meta.data)) 
  nExp_poi.adj <- round(nExp_poi*(1-homotypic.prop))
  tmp <- my_doubletFinder(tmp, PCs = 1:10, pN = 0.25, pK = 0.09, nExp = nExp_poi, reuse.pANN = FALSE)
  tmp <- my_doubletFinder(tmp, PCs = 1:10, pN = 0.25, pK = 0.09, nExp = nExp_poi.adj, reuse.pANN = "pANN")
  DF[[sample]] <- tmp@meta.data[,'DF.classifications',drop=FALSE] %>%
    tibble::rownames_to_column('cell')
}
sobj <- AddMetaData(sobj, do.call(rbind,DF) %>% tibble::remove_rownames() %>% tibble::column_to_rownames('cell'))
DimPlot(sobj,group.by='DF.classifications', order='Doublet')
table(sobj$DF.classifications)
sobj <- subset(sobj, subset=DF.classifications=='Singlet')
```

```{r travaglini}
travaglini <- readRDS('../data/seurat/travaglini_lung_epi.rds')

sobj.subset <- subset(sobj, cells=sample(Cells(sobj), 20000))
anchors <- FindTransferAnchors(reference = travaglini, query = sobj.subset, dims = 1:20,
                               features = intersect(row.names(travaglini@assays$RNA@scale.data),
                                                    row.names(sobj.subset@assays$integrated@scale.data)))
pred <- TransferData(anchorset = anchors, refdata = travaglini$free_annotation, dims = 1:20)
sobj.subset <- AddMetaData(sobj.subset, metadata=pred)
sobj.subset@meta.data %>%
  dplyr::group_by(seurat_clusters,predicted.id) %>%
  dplyr::summarise(n=n()) %>%
  dplyr::mutate(frac=round(n/sum(n),2)) %>%
  dplyr::filter(frac > .1)
DimPlot(sobj.subset, group.by='predicted.id', label=TRUE, repel=TRUE)
```

```{r monocle3}
library(monocle3)
library(SeuratWrappers)

DefaultAssay(sobj) <- 'integrated'
cds <- as.cell_data_set(sobj)

cds <- cluster_cells(cds = cds, reduction_method = "UMAP")
cds <- learn_graph(cds, use_partition = TRUE)
cds <- order_cells(cds, reduction_method = "UMAP",
                   root_cells = Cells(sobj)[sobj$seurat_clusters=='1'])

plot_cells(cds = cds, color_cells_by = "pseudotime", show_trajectory_graph = TRUE)
df <- data.frame(monocle_pseudotime=cds@principal_graph_aux@listData$UMAP$pseudotime,
                 row.names=names(cds@principal_graph_aux@listData$UMAP$pseudotime))
df[!is.finite(df$monocle_pseudotime),'monocle_pseudotime'] <- NA
sobj <- AddMetaData(sobj, df)
``` 

```{r save, cache=FALSE}
saveRDS(sobj,file='../data/seurat/organoids_control.rds')
```
